<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreateTableOrderType extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('order_type', function (Blueprint $table) {
            $table->smallIncrements('id')->comment('类型 ID');
            $table->string('ident', 16)->unique()->comment('英文标识');
            $table->string('name', 30)->comment('中文名称');
            $table->tinyInteger('display')->default(0)->comment('是否显示给用户，0：不显示，1：显示）');
            $table->tinyInteger('operation')->default(0)->comment('账变对余额影响的操作, 0：无操作, 1：加钱，2：扣钱');
            $table->tinyInteger('hold_operation')->default(0)->comment('冻结金额影响的操作, 0：无操作, 1：加钱，2：扣钱');
            $table->smallInteger('category')->default(0)->comment('分类，彩票:1, 冲提:2, 三方：3');
            $table->string('description', 32)->default('')->comment('帐变类型描述');
        });

        $this->_data();
    }

    private function _data()
    {
        $row = DB::table('admin_role_permissions')->where('name', '账变管理')->where('parent_id', 0)->first();

        if (empty($row)) {
            $id = DB::table('admin_role_permissions')->insertGetId([
                'parent_id' => 0,
                'icon' => 'fa-table',
                'rule' => 'orders',
                'name' => '账变管理',
            ]);
        } else {
            $id = $row->id;
        }

        DB::table('admin_role_permissions')->insert(
            [
            'parent_id' => $id,
            'icon' => '',
            'rule' => 'ordertype/index',
            'name' => '账变类型',
            ],
            [
                'parent_id' => $id,
                'icon' => '',
                'rule' => 'ordertype/create',
                'name' => '添加账变类型',
            ],
            [
                'parent_id' => $id,
                'icon' => '',
                'rule' => 'ordertype/edit',
                'name' => '编辑账变类型',
            ],
            [
                'parent_id' => $id,
                'icon' => '',
                'rule' => 'ordertype/delete',
                'name' => '删除账变类型',
            ]
        );

        DB::table('order_type')->insert([
            [
                'name' => '加入游戏',
                'ident' => 'JRYX',
                'display' => 1,
                'operation' => 2,
                'hold_operation' => 1,
                'category' => 1,
                'description' => '彩票投注扣款',
            ],
            [
                'name' => '游戏扣款',
                'ident' => 'YXKK',
                'display' => 0,
                'operation' => 0,
                'hold_operation' => 2,
                'category' => 1,
                'description' => '游戏真实扣款',
            ],
            [
                'name' => '投注返点',
                'ident' => 'TZFD',
                'display' => 1,
                'operation' => 1,
                'hold_operation' => 0,
                'category' => 1,
                'description' => '投注返点',
            ],
            [
                'name' => '奖金派送',
                'ident' => 'JJPS',
                'display' => 1,
                'operation' => 1,
                'hold_operation' => 0,
                'category' => 1,
                'description' => '奖金派送',
            ],
            [
                'name' => '撤单返款',
                'ident' => 'CDFK',
                'display' => 1,
                'operation' => 1,
                'hold_operation' => 2,
                'category' => 1,
                'description' => '撤单返款',
            ],
            //真实扣款后的撤单返款
            [
                'name' => '开奖后撤单返款',
                'ident' => 'CDFKSP',
                'display' => 1,
                'operation' => 1,
                'hold_operation' => 0,
                'category' => 1,
                'description' => '撤单返款',
            ],
            [
                'name' => '撤单手续费',
                'ident' => 'CDSXF',
                'display' => 0,
                'operation' => 2,
                'hold_operation' => 0,
                'category' => 1,
                'description' => '撤单手续费',
            ],
            [
                'name' => '撤销返点',
                'ident' => 'CXFD',
                'display' => 1,
                'operation' => 2,
                'hold_operation' => 0,
                'category' => 1,
                'description' => '撤销返点',
            ],
            [
                'name' => '撤销派奖',
                'ident' => 'CXPJ',
                'display' => 1,
                'operation' => 2,
                'hold_operation' => 0,
                'category' => 1,
                'description' => '撤销派奖',
            ],
            [
                'name' => '追号扣款',
                'ident' => 'ZHKK',
                'display' => 1,
                'operation' => 2,
                'hold_operation' => 1,
                'category' => 1,
                'description' => '追号扣款',
            ],
            [
                'name' => '当期追号返款',
                'ident' => 'DQZHFK',
                'display' => 1,
                'operation' => 1,
                'hold_operation' => 2,
                'category' => 1,
                'description' => '当期追号返款',
            ],
            [
                'name' => '推单佣金(扣)',
                'ident' => 'TDYJD',
                'display' => 1,
                'operation' => 2,
                'hold_operation' => 0,
                'category' => 1,
                'description' => '推单佣金(扣)',
            ],
            [
                'name' => '推单佣金(加)',
                'ident' => 'TDYJA',
                'display' => 1,
                'operation' => 1,
                'hold_operation' => 0,
                'category' => 1,
                'description' => '推单佣金(加)',
            ],
            [
                'name' => '撤销推单佣金(扣)',
                'ident' => 'CXTDYJD',
                'display' => 1,
                'operation' => 2,
                'hold_operation' => 0,
                'category' => 1,
                'description' => '撤销推单佣金(扣)',
            ],
            [
                'name' => '撤销推单佣金(加)',
                'ident' => 'CXTDYJA',
                'display' => 1,
                'operation' => 1,
                'hold_operation' => 0,
                'category' => 1,
                'description' => '撤销推单佣金(加)',
            ],
            [
                'name' => '在线充值',
                'ident' => 'ZXCZ',
                'display' => 1,
                'operation' => 1,
                'hold_operation' => 0,
                'category' => 2,
                'description' => '用户在线支付充值',
            ],
            [
                'name' => '理赔充值',
                'ident' => 'LPCZ',
                'display' => 1,
                'operation' => 1,
                'hold_operation' => 0,
                'category' => 2,
                'description' => '理赔充值',
            ],
            [
                'name' => '促销充值',
                'ident' => 'CXCZ',
                'display' => 1,
                'operation' => 1,
                'hold_operation' => 0,
                'category' => 2,
                'description' => '促销充值',
            ],
            [
                'name' => '现金充值',
                'ident' => 'XJCZ',
                'display' => 1,
                'operation' => 1,
                'hold_operation' => 0,
                'category' => 2,
                'description' => '现金充值',
            ],
            [
                'name' => '人工充值',
                'ident' => 'RGCZ',
                'display' => 1,
                'operation' => 1,
                'hold_operation' => 0,
                'category' => 2,
                'description' => '人工充值',
            ],
            [
                'name' => '上级充值',
                'ident' => 'SJCZ',
                'display' => 1,
                'operation' => 1,
                'hold_operation' => 0,
                'category' => 2,
                'description' => '上级充值',
            ],
            [
                'name' => '跨级充值',
                'ident' => 'KJCZ',
                'display' => 1,
                'operation' => 2,
                'hold_operation' => 0,
                'category' => 2,
                'description' => '上级充值',
            ],
            [
                'name' => '返还手续费',
                'ident' => 'FHSXF',
                'display' => 1,
                'operation' => 1,
                'hold_operation' => 0,
                'category' => 2,
                'description' => '返还手续费',
            ],
            [
                'name' => '积分兑换',
                'ident' => 'JFDH',
                'display' => 1,
                'operation' => 1,
                'hold_operation' => 0,
                'category' => 2,
                'description' => '积分兑换',
            ],
            [
                'name' => '亏损佣金',
                'ident' => 'KSRJ',
                'display' => 1,
                'operation' => 1,
                'hold_operation' => 0,
                'category' => 2,
                'description' => '亏损佣金',
            ],
            [
                'name' => '消费佣金',
                'ident' => 'XFRJ',
                'display' => 1,
                'operation' => 1,
                'hold_operation' => 0,
                'category' => 2,
                'description' => '消费佣金',
            ],
            [
                'name' => '每日工资',
                'ident' => 'MRGZ',
                'display' => 1,
                'operation' => 1,
                'hold_operation' => 0,
                'category' => 2,
                'description' => '每日工资',
            ],
            [
                'name' => '提现申请',
                'ident' => 'TKSQ',
                'display' => 1,
                'operation' => 2,
                'hold_operation' => 1,
                'category' => 2,
                'd escription' => '提现申请',
            ],
            [
                'name' => '提款成功',
                'ident' => 'TKCG',
                'display' => 1,
                'operation' => 0,
                'hold_operation' => 2,
                'category' => 2,
                'description' => '提款成功',
            ],
            [
                'name' => '提款失败',
                'ident' => 'TKSB',
                'display' => 1,
                'operation' => 1,
                'hold_operation' => 2,
                'category' => 2,
                'description' => '提款失败',
            ],
            [
                'name'       => '扣除提款手续费',
                'ident'       => 'TKSXF',
                'display'       => 1,
                'operation'     => 0,
                'hold_operation'      => 2,
                'category' => 2,
                'description'   => '扣除提款手费',
            ],
            [
                'name'       => '返还提款手续费',
                'ident'       => 'FHTKSXF',
                'display'       => 1,
                'operation'     => 1,
                'hold_operation'      => 2,
                'category' => 2,
                'description'   => '返还提款手续费',
            ],

            [
                'name' => '管理员减扣',
                'ident' => 'GLYJK',
                'display' => 1,
                'operation' => 2,
                'hold_operation' => 0,
                'category' => 2,
                'description' => '管理员减扣',
            ],
            [
                'name' => '本人提现',
                'ident' => 'BRTX',
                'display' => 1,
                'operation' => 2,
                'hold_operation' => 0,
                'category' => 2,
                'description' => '本人提现',
            ], [
                'name' => '跨级提现',
                'ident' => 'KJTX',
                'display' => 1,
                'operation' => 2,
                'hold_operation' => 0,
                'category' => 2,
                'description' => '跨级提现',
            ],
            [
                'name' => '充值手续费',
                'ident' => 'CZSXF',
                'display' => 1,
                'operation' => 2,
                'hold_operation' => 0,
                'category' => 2,
                'description' => '充值手续费',
            ],
            [
                'name' => '分红发放',
                'ident' => 'FHFF',
                'display' => 1,
                'operation' => 1,
                'hold_operation' => 0,
                'category' => 2,
                'description' => '分红发放',
            ],
            [
                'name' => 'AG存入',
                'ident' => 'AGCR',
                'display' => 1,
                'operation' => 2,
                'hold_operation' => 0,
                'category' => 3,
                'description' => 'AG存入',
            ],
            [
                'name' => 'AG提取',
                'ident' => 'AGTQ',
                'display' => 1,
                'operation' => 1,
                'hold_operation' => 0,
                'category' => 3,
                'description' => 'AG提取',
            ],
            [
                'name' => 'AG返水',
                'ident' => 'AGFS',
                'display' => 1,
                'operation' => 1,
                'hold_operation' => 0,
                'category' => 3,
                'description' => 'AG返水',
            ],
            [
                'name' => 'BBIN体育存入',
                'ident' => 'BBINSPORTSCR',
                'display' => 1,
                'operation' => 2,
                'hold_operation' => 0,
                'category' => 3,
                'description' => 'BBIN体育存入',
            ],
            [
                'name' => 'BBIN体育提取',
                'ident' => 'BBINSPORTSTQ',
                'display' => 1,
                'operation' => 1,
                'hold_operation' => 0,
                'category' => 3,
                'description' => 'BBIN体育提取',
            ],
            [
                'name' => 'BBIN体育返水',
                'ident' => 'BBINSPORTSFS',
                'display' => 1,
                'operation' => 1,
                'hold_operation' => 0,
                'category' => 3,
                'description' => 'BBIN体育返水',
            ],
            [
                'name' => 'BBIN真人存入',
                'ident' => 'BBINLIVECR',
                'display' => 1,
                'operation' => 2,
                'hold_operation' => 0,
                'category' => 3,
                'description' => 'BBIN真人存入',
            ],
            [
                'name' => 'BBIN真人提取',
                'ident' => 'BBINLIVETQ',
                'display' => 1,
                'operation' => 1,
                'hold_operation' => 0,
                'category' => 3,
                'description' => 'BBIN真人提取',
            ],
            [
                'name' => 'BBIN真人返水',
                'ident' => 'BBINLIVEFS',
                'display' => 1,
                'operation' => 1,
                'hold_operation' => 0,
                'category' => 3,
                'description' => 'BBIN真人返水',
            ],
            [
                'name' => 'SB体育存入',
                'ident' => 'SBCR',
                'display' => 1,
                'operation' => 2,
                'hold_operation' => 0,
                'category' => 3,
                'description' => 'SB体育存入',
            ],
            [
                'name' => 'SB体育提取',
                'ident' => 'SBTQ',
                'display' => 1,
                'operation' => 1,
                'hold_operation' => 0,
                'category' => 3,
                'description' => 'BBIN体育提取',
            ],
            [
                'name' => 'SB体育返水',
                'ident' => 'SBFS',
                'display' => 1,
                'operation' => 1,
                'hold_operation' => 0,
                'category' => 3,
                'description' => 'SB体育返水',
            ],
            [
                'name' => '太阳城存入',
                'ident' => 'SUNBETCR',
                'display' => 1,
                'operation' => 2,
                'hold_operation' => 0,
                'category' => 3,
                'description' => '太阳城存入',
            ],
            [
                'name' => '太阳城提取',
                'ident' => 'SUNBETTQ',
                'display' => 1,
                'operation' => 1,
                'hold_operation' => 0,
                'category' => 3,
                'description' => '太阳城提取',
            ],
            [
                'name' => '太阳城返水',
                'ident' => 'SUNBETFS',
                'display' => 1,
                'operation' => 1,
                'hold_operation' => 0,
                'category' => 3,
                'description' => '太阳城返水',
            ],
            [
                'name' => '竞速加入游戏',
                'ident' => 'VRJRYX',
                'display' => 1,
                'operation' => 2,
                'hold_operation' => 0,
                'category' => 3,
                'description' => '竞速加入游戏',
            ],
            [
                'name' => '竞速追号扣款',
                'ident' => 'VRZHKK',
                'display' => 1,
                'operation' => 2,
                'hold_operation' => 0,
                'category' => 3,
                'description' => '竞速追号扣款',
            ],
            [
                'name' => '竞速投注返点',
                'ident' => 'VRFS',
                'display' => 1,
                'operation' => 1,
                'hold_operation' => 0,
                'category' => 3,
                'description' => '竞速投注返点',
            ],
            [
                'name' => '竞速额外返水',
                'ident' => 'VREXTRAFS',
                'display' => 1,
                'operation' => 1,
                'hold_operation' => 0,
                'category' => 3,
                'description' => '竞速额外返水',
            ],
            [
                'name' => '竞速其他扣款',//给玩家扣钱
                'ident' => 'VRQTKK',
                'display' => 1,
                'operation' => 2,
                'hold_operation' => 0,
                'category' => 3,
                'description' => '竞速其他扣款',
            ],
            [
                'name' => '竞速打赏扣款',//给玩家扣钱
                'ident' => 'VRDSKK',
                'display' => 1,
                'operation' => 2,
                'hold_operation' => 0,
                'category' => 3,
                'description' => '竞速打赏扣款',
            ],
            [
                'name' => '竞速其他入款',//给玩家加钱
                'ident' => 'VRQTRK',
                'display' => 1,
                'operation' => 1,
                'hold_operation' => 0,
                'category' => 3,
                'description' => '竞速其他入款',
            ],
            [
                'name' => '竞速追号返款',//给玩家加钱
                'ident' => 'VRZHFK',
                'display' => 1,
                'operation' => 1,
                'hold_operation' => 0,
                'category' => 3,
                'description' => '竞速追号返款',
            ],
            [
                'name' => '竞速撤单返款',//给玩家加钱
                'ident' => 'VRCDFK',
                'display' => 1,
                'operation' => 1,
                'hold_operation' => 0,
                'category' => 3,
                'description' => '竞速撤单返款',
            ],
            [
                'name' => '竞速奖金派送',//给玩家加钱
                'ident' => 'VRJJPS',
                'display' => 1,
                'operation' => 1,
                'hold_operation' => 0,
                'category' => 3,
                'description' => '竞速奖金派送',
            ],
            [
                'name' => 'EBET存入',
                'ident' => 'EBETCR',
                'display' => 1,
                'operation' => 2,
                'hold_operation' => 0,
                'category' => 3,
                'description' => 'EBET存入',
            ],
            [
                'name' => 'EBET提取',
                'ident' => 'EBETTQ',
                'display' => 1,
                'operation' => 1,
                'hold_operation' => 0,
                'category' => 3,
                'description' => 'EBET提取',
            ],
            [
                'name' => 'EBET返水',
                'ident' => 'EBETFS',
                'display' => 1,
                'operation' => 1,
                'hold_operation' => 0,
                'category' => 3,
                'description' => 'EBET返水',
            ],
            [
                'name' => 'UG存入',
                'ident' => 'UGCR',
                'display' => 0,
                'operation' => 2,
                'hold_operation' => 0,
                'category' => 3,
                'description' => 'UG存入',
            ],
            [
                'name' => 'UG提取',
                'ident' => 'UGTQ',
                'display' => 0,
                'operation' => 1,
                'hold_operation' => 0,
                'category' => 3,
                'description' => 'UG提取',
            ],
            [
                'name' => 'UG返水',
                'ident' => 'UGFS',
                'display' => 0,
                'operation' => 1,
                'hold_operation' => 0,
                'category' => 3,
                'description' => 'UG返水',
            ],
            [
                'name' => '契约分红发放',
                'ident' => 'QYFHFF',
                'display' => 1,
                'operation' => 2,
                'hold_operation' => 0,
                'category' => 2,
                'description' => '契约分红发放',
            ],
            [
                'name' => '契约分红领取',
                'ident' => 'QYFHLQ',
                'display' => 1,
                'operation' => 1,
                'hold_operation' => 0,
                'category' => 2,
                'description' => '契约分红领取',
            ],
            [
                'name' => 'IM电竞存入',
                'ident' => 'IMCR',
                'display' => 1,
                'operation' => 2,
                'hold_operation' => 0,
                'category' => 3,
                'description' => 'IM电竞(cia)存入',
            ],
            [
                'name' => 'IM电竞提取',
                'ident' => 'IMTQ',
                'display' => 1,
                'operation' => 1,
                'hold_operation' => 0,
                'category' => 3,
                'description' => 'IM电竞(cia)提取',
            ],
            [
                'name' => 'IM电竞返水',
                'ident' => 'IMFS',
                'display' => 1,
                'operation' => 1,
                'hold_operation' => 0,
                'category' => 3,
                'description' => 'IM电竞返水',
            ],
            [
                'name' => 'PT存入',
                'ident' => 'PTCR',
                'display' => 1,
                'operation' => 2,
                'hold_operation' => 0,
                'category' => 3,
                'description' => 'PT存入',
            ],
            [
                'name' => 'PT提取',
                'ident' => 'PTTQ',
                'display' => 1,
                'operation' => 1,
                'hold_operation' => 0,
                'category' => 3,
                'description' => 'PT提取',
            ],
            [
                'name' => 'PT返水',
                'ident' => 'PTFS',
                'display' => 1,
                'operation' => 1,
                'hold_operation' => 0,
                'category' => 3,
                'description' => 'PT返水',
            ],
            [
                'name' => 'KY棋牌存入',
                'ident' => 'KYCR',
                'display' => 1,
                'operation' => 2,
                'hold_operation' => 0,
                'category' => 3,
                'description' => 'KY棋牌存入',
            ],
            [
                'name' => 'KY棋牌提取',
                'ident' => 'KYTQ',
                'display' => 1,
                'operation' => 1,
                'hold_operation' => 0,
                'category' => 3,
                'description' => 'KY棋牌提取',
            ],
            [
                'name' => 'KY棋牌返水',
                'ident' => 'KYFS',
                'display' => 1,
                'operation' => 1,
                'hold_operation' => 0,
                'category' => 3,
                'description' => 'KY棋牌返水',
            ],
            [
                'name' => 'AB存入',
                'ident' => 'ABCR',
                'display' => 1,
                'operation' => 2,
                'hold_operation' => 0,
                'category' => 3,
                'description' => '欧博存入',
            ],
            [
                'name' => 'AB真人提取',
                'ident' => 'ABTQ',
                'display' => 1,
                'operation' => 1,
                'hold_operation' => 0,
                'category' => 3,
                'description' => '欧博真人提取',
            ],
            [
                'name' => 'AB真人返水',
                'ident' => 'ABFS',
                'display' => 1,
                'operation' => 1,
                'hold_operation' => 0,
                'category' => 3,
                'description' => '欧博真人返水',
            ],
            [
                'name' => '乐利投注扣款',
                'ident' => 'FHLELIJRYX',
                'display' => 1,
                'operation' => 2,
                'hold_operation' => 0,
                'category' => 3,
                'description' => '乐利投注扣款',
            ],
            [
                'name' => '乐利追号扣款',
                'ident' => 'FHLELIZHKK',
                'display' => 1,
                'operation' => 2,
                'hold_operation' => 0,
                'category' => 3,
                'description' => '乐利追号扣款',
            ],
            [
                'name' => '乐利打赏扣款',
                'ident' => 'FHLELIDSKK',
                'display' => 1,
                'operation' => 2,
                'hold_operation' => 0,
                'category' => 3,
                'description' => '乐利打赏扣款',
            ],
            [
                'name' => '乐利系统撤单奖金回扣',
                'ident' => 'FHLELIXTCDJJHK',
                'display' => 1,
                'operation' => 2,
                'hold_operation' => 0,
                'category' => 3,
                'description' => '乐利系统撤单奖金回扣',
            ],
            [
                'name' => '乐利中奖停止追号入款',
                'ident' => 'FHLELIZZTZZHRK',
                'display' => 1,
                'operation' => 1,
                'hold_operation' => 0,
                'category' => 3,
                'description' => '乐利中奖停止追号入款',
            ],
            [
                'name' => '乐利投注撤单入款',
                'ident' => 'FHLELITZCDRK',
                'display' => 1,
                'operation' => 1,
                'hold_operation' => 0,
                'category' => 3,
                'description' => '乐利投注撤单入款',
            ],
            [
                'name' => '乐利追号撤单入款',
                'ident' => 'FHLELIZHCDRK',
                'display' => 1,
                'operation' => 1,
                'hold_operation' => 0,
                'category' => 3,
                'description' => '乐利追号撤单入款',
            ],
            [
                'name' => '乐利中奖派送入款',
                'ident' => 'FHLELIZJPSRK',
                'display' => 1,
                'operation' => 1,
                'hold_operation' => 0,
                'category' => 3,
                'description' => '乐利中奖派送入款',
            ],
            [
                'name' => '乐利系统撤单入款',
                'ident' => 'FHLELIXTCDRK',
                'display' => 1,
                'operation' => 1,
                'hold_operation' => 0,
                'category' => 3,
                'description' => '乐利系统撤单入款',
            ],
            [
                'name' => '乐利返水',
                'ident' => 'FHLELIFS',
                'display' => 1,
                'operation' => 1,
                'hold_operation' => 0,
                'category' => 3,
                'description' => '乐利返水',
            ],
            [
                'name' => 'GG棋牌存入',
                'ident' => 'GGQIPAICR',
                'display' => 1,
                'operation' => 2,
                'hold_operation' => 0,
                'category' => 3,
                'description' => 'GG棋牌存入',
            ],
            [
                'name' => 'GG棋牌提取',
                'ident' => 'GGQIPAITQ',
                'display' => 1,
                'operation' => 1,
                'hold_operation' => 0,
                'category' => 3,
                'description' => 'GG棋牌提取',
            ],
            [
                'name' => 'GG棋牌返水',
                'ident' => 'GGQIPAIFS',
                'display' => 1,
                'operation' => 1,
                'hold_operation' => 0,
                'category' => 3,
                'description' => 'GG棋牌返水',
            ],
            [
                'name' => 'GG电游存入',
                'ident' => 'GGDYCR',
                'display' => 1,
                'operation' => 2,
                'hold_operation' => 0,
                'category' => 3,
                'description' => 'GG电游存入',
            ],
            [
                'name' => 'GG电游提取',
                'ident' => 'GGDYTQ',
                'display' => 1,
                'operation' => 1,
                'hold_operation' => 0,
                'category' => 3,
                'description' => 'GG电游提取',
            ],
            [
                'name' => 'GG电游返水',
                'ident' => 'GGDYFS',
                'display' => 1,
                'operation' => 1,
                'hold_operation' => 0,
                'category' => 3,
                'description' => 'GG电游返水',
            ],
            [
                'name' => '利记体育存入',
                'ident' => 'SBOCR',
                'display' => 1,
                'operation' => 2,
                'hold_operation' => 0,
                'category' => 3,
                'description' => '利记体育存入',
            ],
            [
                'name' => '利记体育提取',
                'ident' => 'SBOTQ',
                'display' => 1,
                'operation' => 1,
                'hold_operation' => 0,
                'category' => 3,
                'description' => '利记体育提取',
            ],
            [
                'name' => '利记体育返水',
                'ident' => 'SBOFS',
                'display' => 1,
                'operation' => 1,
                'hold_operation' => 0,
                'category' => 3,
                'description' => '利记体育返水',
            ],
            [
                'name' => '幸运棋牌存入',
                'ident' => 'LGQPCR',
                'display' => 1,
                'operation' => 2,
                'hold_operation' => 0,
                'category' => 3,
                'description' => '利幸运棋牌存入',
            ],
            [
                'name' => '幸运棋牌提取',
                'ident' => 'LGQPTQ',
                'display' => 1,
                'operation' => 1,
                'hold_operation' => 0,
                'category' => 3,
                'description' => '幸运棋牌提取',
            ],
            [
                'name' => '幸运棋牌返水',
                'ident' => 'LGQPFS',
                'display' => 1,
                'operation' => 1,
                'hold_operation' => 0,
                'category' => 3,
                'description' => '幸运棋牌返水',
            ],
            [
                'name' => '龙城棋牌存入',
                'ident' => 'LCQPCR',
                'display' => 1,
                'operation' => 2,
                'hold_operation' => 0,
                'category' => 3,
                'description' => '利龙城棋牌存入',
            ],
            [
                'name' => '龙城棋牌提取',
                'ident' => 'LCQPTQ',
                'display' => 1,
                'operation' => 1,
                'hold_operation' => 0,
                'category' => 3,
                'description' => '龙城棋牌提取',
            ],
            [
                'name' => '龙城棋牌返水',
                'ident' => 'LCQPFS',
                'display' => 1,
                'operation' => 1,
                'hold_operation' => 0,
                'category' => 3,
                'description' => '龙城棋牌返水',
            ],
            [
                'name' => '财神棋牌存入',
                'ident' => 'VGQPCR',
                'display' => 1,
                'operation' => 2,
                'hold_operation' => 0,
                'category' => 3,
                'description' => '利财神棋牌存入',
            ],
            [
                'name' => '财神棋牌提取',
                'ident' => 'VGQPTQ',
                'display' => 1,
                'operation' => 1,
                'hold_operation' => 0,
                'category' => 3,
                'description' => '财神棋牌提取',
            ],
            [
                'name' => '财神棋牌返水',
                'ident' => 'VGQPFS',
                'display' => 1,
                'operation' => 1,
                'hold_operation' => 0,
                'category' => 3,
                'description' => '财神棋牌返水',
            ],
            [
                'name' => 'MG电游存入',
                'ident' => 'MGDYCR',
                'display' => 1,
                'operation' => 2,
                'hold_operation' => 0,
                'category' => 3,
                'description' => 'MG电游存入',
            ],
            [
                'name' => 'MG电游提取',
                'ident' => 'MGDYTQ',
                'display' => 1,
                'operation' => 1,
                'hold_operation' => 0,
                'category' => 3,
                'description' => 'MG电游提取',
            ],
            [
                'name' => 'MG电游返水',
                'ident' => 'MGDYFS',
                'display' => 1,
                'operation' => 1,
                'hold_operation' => 0,
                'category' => 3,
                'description' => 'MG电游返水',
            ],
            [
                'name' => 'BNG电游存入',
                'ident' => 'BNGDYCR',
                'display' => 1,
                'operation' => 2,
                'hold_operation' => 0,
                'category' => 3,
                'description' => 'BNG电游存入',
            ],
            [
                'name' => 'BNG电游提取',
                'ident' => 'BNGDYTQ',
                'display' => 1,
                'operation' => 1,
                'hold_operation' => 0,
                'category' => 3,
                'description' => 'BNG电游提取',
            ],
            [
                'name' => 'BNG电游返水',
                'ident' => 'BNGDYFS',
                'display' => 1,
                'operation' => 1,
                'hold_operation' => 0,
                'category' => 3,
                'description' => 'BNG电游返水',
            ],
            [
                'name' => 'TCG体育存入',
                'ident' => 'TCGCR',
                'display' => 1,
                'operation' => 2,
                'hold_operation' => 0,
                'category' => 3,
                'description' => 'TCG体育存入',
            ],
            [
                'name' => 'TCG体育提取',
                'ident' => 'TCGTQ',
                'display' => 1,
                'operation' => 1,
                'hold_operation' => 0,
                'category' => 3,
                'description' => 'TCG体育提取',
            ],
            [
                'name' => 'TCG体育返水',
                'ident' => 'TCGFS',
                'display' => 1,
                'operation' => 1,
                'hold_operation' => 0,
                'category' => 3,
                'description' => 'TCG体育返水',
            ],
            [
                'name' => 'AIO沙巴体育存入',
                'ident' => 'AIOCR',
                'display' => 1,
                'operation' => 2,
                'hold_operation' => 0,
                'category' => 3,
                'description' => 'AIO沙巴体育存入',
            ],
            [
                'name' => 'AIO沙巴体育提取',
                'ident' => 'AIOTQ',
                'display' => 1,
                'operation' => 1,
                'hold_operation' => 0,
                'category' => 3,
                'description' => 'AIO沙巴体育提取',
            ],
            [
                'name' => 'AIO沙巴体育返水',
                'ident' => 'AIOFS',
                'display' => 1,
                'operation' => 1,
                'hold_operation' => 0,
                'category' => 3,
                'description' => 'AIO沙巴体育返水',
            ],
            [
                'name' => '完美真人存入',
                'ident' => 'WMLCR',
                'display' => 1,
                'operation' => 2,
                'hold_operation' => 0,
                'category' => 3,
                'description' => '完美真人存入',
            ],
            [
                'name' => '完美真人提取',
                'ident' => 'WMLTQ',
                'display' => 1,
                'operation' => 1,
                'hold_operation' => 0,
                'category' => 3,
                'description' => '完美真人提取',
            ],
            [
                'name' => '完美真人返水',
                'ident' => 'WMLFS',
                'display' => 1,
                'operation' => 1,
                'hold_operation' => 0,
                'category' => 3,
                'description' => '完美真人返水',
            ],
            [
                'name' => '乐游棋牌存入',
                'ident' => 'LEGCR',
                'display' => 1,
                'operation' => 2,
                'hold_operation' => 0,
                'category' => 3,
                'description' => '乐游棋牌存入',
            ],
            [
                'name' => '乐游棋牌提取',
                'ident' => 'LEGTQ',
                'display' => 1,
                'operation' => 1,
                'hold_operation' => 0,
                'category' => 3,
                'description' => '乐游棋牌提取',
            ],
            [
                'name' => '乐游棋牌返水',
                'ident' => 'LEGFS',
                'display' => 1,
                'operation' => 1,
                'hold_operation' => 0,
                'category' => 3,
                'description' => '乐游棋牌返水',
            ],
            [
                'name' => '泛亚电竞存入',
                'ident' => 'AVIACR',
                'display' => 1,
                'operation' => 2,
                'hold_operation' => 0,
                'category' => 3,
                'description' => '泛亚电竞存入',
            ],
            [
                'name' => '泛亚电竞提取',
                'ident' => 'AVIATQ',
                'display' => 1,
                'operation' => 1,
                'hold_operation' => 0,
                'category' => 3,
                'description' => '泛亚电竞提取',
            ],
            [
                'name' => '泛亚电竞返水',
                'ident' => 'AVIAFS',
                'display' => 1,
                'operation' => 1,
                'hold_operation' => 0,
                'category' => 3,
                'description' => '泛亚电竞返水',
            ],
            [
                'name' => 'MG2电游存入',
                'ident' => 'MG2CR',
                'display' => 1,
                'operation' => 2,
                'hold_operation' => 0,
                'category' => 3,
                'description' => 'MG2电游存入',
            ],
            [
                'name' => 'MG2电游提取',
                'ident' => 'MG2TQ',
                'display' => 1,
                'operation' => 1,
                'hold_operation' => 0,
                'category' => 3,
                'description' => 'MG2电游提取',
            ],
            [
                'name' => 'MG2电游返水',
                'ident' => 'MG2FS',
                'display' => 1,
                'operation' => 1,
                'hold_operation' => 0,
                'category' => 3,
                'description' => 'MG2电游返水',
            ],
            [
                'name' => 'BG大游存入',
                'ident' => 'BGCR',
                'display' => 1,
                'operation' => 2,
                'hold_operation' => 0,
                'category' => 3,
                'description' => 'BG大游存入',
            ],
            [
                'name' => 'BG大游提取',
                'ident' => 'BGTQ',
                'display' => 1,
                'operation' => 1,
                'hold_operation' => 0,
                'category' => 3,
                'description' => 'BG大游提取',
            ],
            [
                'name' => 'BG大游返水',
                'ident' => 'BGFS',
                'display' => 1,
                'operation' => 1,
                'hold_operation' => 0,
                'category' => 3,
                'description' => 'BG大游返水',
            ],
            [
                'name' => 'DS电竞存入',
                'ident' => 'DSCR',
                'display' => 1,
                'operation' => 2,
                'hold_operation' => 0,
                'category' => 3,
                'description' => 'DS电竞存入',
            ],
            [
                'name' => 'DS电竞提取',
                'ident' => 'DSTQ',
                'display' => 1,
                'operation' => 1,
                'hold_operation' => 0,
                'category' => 3,
                'description' => 'DS电竞提取',
            ],
            [
                'name' => 'DS电竞返水',
                'ident' => 'DSFS',
                'display' => 1,
                'operation' => 1,
                'hold_operation' => 0,
                'category' => 3,
                'description' => 'DS电竞返水',
            ],
            [
                'name' => '投注服务费',
                'ident' => 'TZFWF',
                'display' => 1,
                'operation' => 2,
                'hold_operation' => 0,
                'category' => 1,
                'description' => '投注服务费',
            ],
            [
                'name' => '返还投注服务费',
                'ident' => 'FHTZFWF',
                'display' => 1,
                'operation' => 1,
                'hold_operation' => 0,
                'category' => 1,
                'description' => '返还投注服务费',
            ],[
                'name' => '追号服务费',
                'ident' => 'ZHFWF',
                'display' => 1,
                'operation' => 2,
                'hold_operation' => 1,
                'category' => 1,
                'description' => '追号服务费',
            ],
            [
                'name' => '当期追号服务费返款',
                'ident' => 'DQZHFWFFK',
                'display' => 1,
                'operation' => 1,
                'hold_operation' => 2,
                'category' => 1,
                'description' => '当期追号服务费返款',
            ],
            [
                'name' => '追号服务费返款',
                'ident' => 'ZHFWFFK',
                'display' => 1,
                'operation' => 1,
                'hold_operation' => 2,
                'category' => 1,
                'description' => '追号服务费返款',
            ],
            [
                'name' => '向上级转账',
                'ident' => 'XSJZZ',
                'display' => 1,
                'operation' => 2,
                'hold_operation' => 0,
                'category' => 0,
                'description' => '向上级转账',
            ],
            [
                'name' => '从下级转入',
                'ident' => 'CXJZR',
                'display' => 1,
                'operation' => 1,
                'hold_operation' => 0,
                'category' => 0,
                'description' => '从下级转入',
            ],
            [
                'name' => '冻结金额增加',
                'ident' => 'DJJEZJ',
                'display' => 0,
                'operation' => 0,
                'hold_operation' => 1,
                'category' => 2,
                'description' => '冻结金额增加',
            ],
            [
                'name' => '冻结金额扣除',
                'ident' => 'DJJEKC',
                'display' => 0,
                'operation' => 0,
                'hold_operation' => 2,
                'category' => 2,
                'description' => '冻结金额扣除',
            ],
            [
                'name' => '活动异常盈利扣减',
                'ident' => 'YCYLKJ',
                'display' => 1,
                'operation' => 2,
                'hold_operation' => 0,
                'category' => 2,
                'description' => '活动异常盈利扣减',
            ],
            [
                'name' => '三方异常盈利扣减',
                'ident' => 'SFYCYLKJ',
                'display' => 1,
                'operation' => 2,
                'hold_operation' => 0,
                'category' => 2,
                'description' => '三方异常盈利扣减',
            ],
            [
                'name' => '代理私返发放',
                'ident' => 'SFFF',
                'display' => 1,
                'operation' => 2,
                'hold_operation' => 0,
                'category' => 2,
                'description' => '代理私返发放[-]',
            ],
            [
                'name' => '代理私返领取',
                'ident' => 'SFLQ',
                'display' => 1,
                'operation' => 1,
                'hold_operation' => 0,
                'category' => 2,
                'description' => '代理私返领取[+]',
            ],
            [
                'name' => '系统佣金发放',
                'ident' => 'XTYJFF',
                'display' => 1,
                'operation' => 1,
                'hold_operation' => 0,
                'category' => 2,
                'description' => '系统佣金发放[+]',
            ],
            [
                'name' => '系统私返发放',
                'ident' => 'XTSFFF',
                'display' => 1,
                'operation' => 1,
                'hold_operation' => 0,
                'category' => 2,
                'description' => '系统私返发放[+]',
            ],
            [
                'name' => '三方人工充值',
                'ident' => 'SFRGCZ',
                'display' => 1,
                'operation' => 1,
                'hold_operation' => 0,
                'category' => 2,
                'description' => '三方人工充值[+]',
            ],
            [
                'name' => '系统经营扣款',
                'ident' => 'XTJYKK',
                'display' => 1,
                'operation' => 2,
                'hold_operation' => 0,
                'category' => 2,
                'description' => '系统经营扣款[-]',
            ],[
                'name' => '彩票抽水',
                'ident' => 'CPCS',
                'display' => 1,
                'operation' => 2,
                'hold_operation' => 0,
                'category' => 1,
                'description' => '彩票抽水扣款[-]',
            ],[
                'name' => '彩票返水',
                'ident' => 'CPFS',
                'display' => 1,
                'operation' => 1,
                'hold_operation' => 0,
                'category' => 1,
                'description' => '彩票返水加款[+]',
            ], [
                'name' => 'SEA电游存入',
                'ident' => 'SEACR',
                'display' => 1,
                'operation' => 2,
                'hold_operation' => 0,
                'category' => 3,
                'description' => 'SEA电游存入',
            ],
            [
                'name' => 'SEA电游提取',
                'ident' => 'SEATQ',
                'display' => 1,
                'operation' => 1,
                'hold_operation' => 0,
                'category' => 3,
                'description' => 'SEA电游提取',
            ],
            [
                'name' => 'SEA电游返水',
                'ident' => 'SEAFS',
                'display' => 1,
                'operation' => 1,
                'hold_operation' => 0,
                'category' => 3,
                'description' => 'SEA电游返水',
            ],
        ]);
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        if (app()->environment() != 'production') {
            Schema::dropIfExists('order_type');
        }
    }
}
